### ISSUE TITLE
Page error logging and requests validation

### ISSUE THREAD

**Issue by umitskevich** [paralect/pdf-service#14]
1. Please add the following code so we can see if there are any errors when page is rendered
```
page.on('console', (...args) => logger.info('PAGE LOG:', ...args));

page.on('error', (err) => {
  logger.error(`Error event emitted: ${err}`);
  logger.error(err.stack);
  closeBrowser(browser);
});
```

 2. It would be great to add options validation, it can be just Joi schema like in ship api. pdf and screenshot methods of puppeteer have different options and by validating options we can prevent service from passing incorrect params to browser

**Comment by KuhArt** [comment]
Could you check this pr https://github.com/paralect/pdf-service/pull/15 . Maybe I missed something?

**Comment by KuhArt** [comment]
Updated.
