### ISSUE TITLE
handlebars partials rendering

### ISSUE THREAD

**Issue by NesterenkoNikita** [paralect/pdf-service#6]
It would be nice if `generatePdf` and `generatePdfByContent` functions could take `templatePartials` option as well
[partials](http://handlebarsjs.com/partials.html)

**Comment by KuhArt** [comment]
https://github.com/paralect/pdf-service/pull/7 partials in this pr
But I change some generate method params. You should use
`{
templateSystem: {
 params,
helpers,
partials,
}
}`

Find more in docs https://github.com/paralect/pdf-service/blob/master/client/samples/harvestReport/index.js
I'm going to update docs in the nearest future.

**Comment by NesterenkoNikita** [comment]
@KuhArt that's great. thanks!

**Comment by anorsich** [comment]
@KuhArt I think we can close this question, but open another issue to create a better documentation for the pdf-service. [Here](https://github.com/paralect/node-mongo/blob/master/API.md) is a good example :)
