### ISSUE TITLE
possibility to put handlebars to headerTemplate and footerTemplate options

### ISSUE THREAD

**Issue by NesterenkoNikita** [paralect/pdf-service#8]
`puppeteer` has `headerTemplate` and `footerTemplate` options that takes html. Would be nice if client could take handlebars for this options

**Comment by KuhArt** [comment]
https://github.com/paralect/pdf-service/pull/11

**Comment by anorsich** [comment]
@KuhArt Can we close this issue? Pull request seems to be merged already.
